### ISSUE TITLE
Unable to translate routes

### ISSUE THREAD

**Issue by barbudreadmon** [jenyak/I18nRoutingServiceProvider#1]
I've been trying to use your package, i did a simple test with the following code : 

require __DIR__.'/../vendor/autoload.php';

$app = new Silex\Application();

$app->register(new Silex\Provider\TranslationServiceProvider());
$app->register(new Jenyak\I18nRouting\Provider\I18nRoutingServiceProvider());
$app['locale'] = 'en';
$app['i18n_routing.locales'] = array('en', 'hu', 'ua');

// You can translate patterns
$app['translator.domains'] = array('routes' => array(
    'hu' => array('test_route' => '/teszt'),
));

// There's no need to put {_locale} in route pattern
$app->get('/test', function () {
   phpinfo();
})->bind('test_route');

But /test returns my phpinfo, but /hu/teszt returns "Sorry, the page you are looking for could not be found."
Do i need some specific version of silex to use this package ? Which one ? i'm currently using v1.3.1

**Comment by jenyak** [comment]
I have update this packege on packagist.org. It should work now.
Silex > 1.3 is ok.
