### ISSUE TITLE
Silex 1.3 compatibility

### ISSUE THREAD

**Issue by ehibes** [jenyak/I18nRoutingServiceProvider#6]
I've forked your project. Executing phpunit tests failing with php 5.5 silex 1.3 on branch 1.0. 
Can you launch a travis ci build on 1.0 branch?

**Comment by jenyak** [comment]
@ehibes, I add php 5.5, 5.6 to 1.0 branch and it seem that all tests passed

**Comment by ehibes** [comment]
@jenyak I made a [video](https://youtu.be/jnXEm2HElpg) to show you my issue. Perhaps a php extension is missing?

**Comment by jenyak** [comment]
Did you try it in another environment? Only 1 test fail so maybe it some cyrillic/encoding related issue, try to replace `тест` in file [I18nRoutingServiceProviderTest.php](https://github.com/jenyak/I18nRoutingServiceProvider/blob/1.0/tests/I18nRoutingServiceProviderTest.php) at line 21, 57 to some latin word.

**Comment by ehibes** [comment]
Oh yes, it's that! Now it works. Thanks!

**Comment by jenyak** [comment]
@ehibes can you give me your `phpinfo();` ?

**Comment by ehibes** [comment]
@jenyak [here](https://jsfiddle.net/ho0uvbrL/)

**Comment by jenyak** [comment]
I'm sure it depends on the environment but I can not identify the exact reason.

**Comment by ehibes** [comment]
I'm working on MacOS. Perhaps it's because of that. You can close this issue, all travis tests pass.
